### ISSUE TITLE
index.htmlにheadタグとbodyタグを書いてみる

### ISSUE THREAD

**Issue by shikeccchan** [kanatei/kanatei.github.io#1]

**Comment by kanatei** [comment]
どうやって編集するの？

**Comment by shikeccchan** [comment]
デスクトップからSublime Textを開いて、左上の `File` から `Open` を選んで

![](https://i.ibb.co/QnZ3BDS/2021-06-09-18-46-32.png)

```
kana > github-pages > index.html
```

のファイルを開くと、エディタで編集できるようになるよ

**Comment by kanatei** [comment]
とりあえずheadの定型文みたいなのは書いてみたけど
大枠とはそういうことであってる？
まあCSSできてないからheadも完成してないけど！

**Comment by shikeccchan** [comment]
あってるよ〜 👍 

headは別に
```css
<link rel="stylesheet" href="style.css">
```

みたいなのを入れなくても動くしあとから必要な分を足せばいいからこのタスクではそこまで書くのを想定していないよ 🙆‍♂️

**Comment by shikeccchan** [comment]
かけたら
```bash
$ git add index.html
$ git commit -m "headタグ追加"
$ git push origin master
```
などとして反映させてみてね

**Comment by kanatei** [comment]
css作ったってやったけどできてる？

**Comment by shikeccchan** [comment]
できてないね〜
cssを作ったってことは
```bash
$ touch style.css
```

したってこと？

それなら
```bash
$ git add style.css
```
もしないとコミットには反映されないよ〜

**Comment by shikeccchan** [comment]
エラー出てる気がするなら手元のコマンドとエラーを全部コピペしてここに貼ってくれると見るよ

**Comment by kanatei** [comment]
$ git add style.css                                     master [~/github-pages]
$ git commit  -m "css作った"                            master [~/github
[master f09c865] css作った
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 style.css
$ git push kanatei master                               master [~/github-page
fatal: 'kanatei' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
$ git push origin                                       master [~/github-pages]
fatal: The current branch master has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin master

$ git add index.html                                    master [~/github-page
$ git commit -m "headタグ追加"                          master [~/github-pages]
On branch master
nothing to commit, working tree clean

**Comment by shikeccchan** [comment]
コード貼るとき
https://docs.github.com/ja/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks
を参考にして、
```
`
```
3つで挟むときれいに貼れるよ

**Comment by shikeccchan** [comment]
上のメッセージにある通り
```
$ git push --set-upstream origin master
```

やってみてもらえる？

**Comment by shikeccchan** [comment]
無理だったら
```bash
$ git remote -v
```
の結果見せて

**Comment by kanatei** [comment]
CSSはできた！
