### ISSUE TITLE
ファイルを編集し終わったけどどうやってページに反映させるの？

### ISSUE THREAD

**Issue by kanatei** [kanatei/kanatei.github.io#2]

**Comment by shikeccchan** [comment]
https://github.com/xuzijian629/git-how-to/wiki/チュートリアル（3:-ファイルの編集編）

ここに、ターミナルでファイルを編集し終わった後にGitHubにpushする方法が載ってるから、これを実行するといけるよ

kanatei.github.ioというプロジェクト（これ）は https://kanatei.github.io と連動していて、ここのmasterブランチが更新されると、しばらくするとウェブページも更新されるよ
